### PR TITLE
Specify value type of property

### LINKED ISSUE #45: Getting classname or subclass
In order to access the values, I need to now which subclass of ReadValue I get. ```obj.constructor.name``` does not work in minified code.

We should add an ```is A``property with symbols... (see my simplifier...)

https://github.com/dasch-swiss/knora-jsonld-simplify/blob/ad7cddbad28debb15863263aa83b3ad820d99d3f/src/KnoraValue.ts#L7-L10

### PR DESCRIPTION
**Pull request by tobiasschweizer**
implements #54
closes #45

### CODE REVIEW

File: src/models/v2/resources/read-resource.ts [hunk 1]
```diff
@@ -71,4 +72,17 @@ export class ReadResource {
         }
     }
 
+    getValuesAs<T>(property: string, valueType: ResourcesConversionUtil.Constructor<T>): T[] {
```
Comment (tobiasschweizer) [inline src/models/v2/resources/read-resource.ts]: `T`should be restricted to a subclass of `ReadValue`: https://www.typescriptlang.org/docs/handbook/generics.html#using-class-types-in-generics

**Comment by tobiasschweizer** [comment]
```
WARNING in Circular dependency detected:
.yalc/@knora/api/src/models/v2/resources/ResourcesConversionUtil.js -> .yalc/@knora/api/src/models/v2/resources/read-resource.js -> .yalc/@knora/api/src/models/v2/resources/ResourcesConversionUtil.js

WARNING in Circular dependency detected:
.yalc/@knora/api/src/models/v2/resources/read-resource.js -> .yalc/@knora/api/src/models/v2/resources/ResourcesConversionUtil.js -> .yalc/@knora/api/src/models/v2/resources/read-resource.js
```

**Comment by tobiasschweizer** [comment]
> Please export Constants and CountQueryResponse

https://github.com/dhlab-basel/knora-api-js-lib/pull/46/commits/6511a48384efeec1c37e1d4d3729ebf379b7cad1

**Comment by tobiasschweizer** [comment]
@lrosenth A property's object type can be gotten from the ontology information we already have, see https://github.com/dhlab-basel/knora-api-js-lib/pull/46/commits/c4ae2e8fff35e9511b5a49fc41476a7298ddcedd
